wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    code_path: code/weightsbiases.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
    t:
      1:
      - 1
      2:
      - 1
      4: 3.6.12
      5: 0.11.0
      8:
      - 5
policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 25000
