wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_episode_num:
  desc: null
  value: 0
_last_dones:
  desc: null
  value: '[False]'
_last_obs:
  desc: null
  value: '[[ 0.0459163  -0.03367535  0.00590822 -0.02245776]]'
_last_original_obs:
  desc: null
  value: None
_n_updates:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 25000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    code_path: code/weightsbiases.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 3
      4: 3.6.12
      5: 0.11.0
      8:
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Discrete(2)
batch_size:
  desc: null
  value: 64
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fd9c8084268>
clip_range_vf:
  desc: null
  value: None
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: 0.0
env:
  desc: null
  value: <stable_baselines3.common.vec_env.vec_video_recorder.VecVideoRecorder object
    at 0x7fd9eb64f780>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.0003
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fd9e9f59d90>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 1
n_epochs:
  desc: null
  value: 10
n_steps:
  desc: null
  value: 2048
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: Box(-3.4028234663852886e+38, 3.4028234663852886e+38, (4,), float32)
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor): MlpExtractor(\n  \
    \  (shared_net): Sequential()\n    (policy_net): Sequential(\n      (0): Linear(in_features=4,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=4, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=2, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
  desc: null
  value: '{}'
policy_type:
  desc: null
  value: MlpPolicy
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7fd9e9f52630>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1626877684.437183
target_kl:
  desc: null
  value: None
tensorboard_log:
  desc: null
  value: runs/PPO_1626877681
total_timesteps:
  desc: null
  value: 25000
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
vf_coef:
  desc: null
  value: 0.5
