wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_episode_num:
  desc: null
  value: 0
_last_dones:
  desc: null
  value: '[False]'
_last_obs:
  desc: null
  value: '[[ 0.01829203 -0.01484141  0.00339176  0.03961374]]'
_last_original_obs:
  desc: null
  value: None
_n_updates:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 25000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    code_path: code/dqn-sb3.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 3
      4: 3.6.12
      5: 0.11.0
      8:
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Discrete(2)
actor:
  desc: null
  value: None
batch_size:
  desc: null
  value: 32
buffer_size:
  desc: null
  value: 1000000
device:
  desc: null
  value: cpu
env:
  desc: null
  value: <stable_baselines3.common.vec_env.vec_video_recorder.VecVideoRecorder object
    at 0x7ffaf02ac3c8>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
exploration_final_eps:
  desc: null
  value: 0.05
exploration_fraction:
  desc: null
  value: 0.1
exploration_initial_eps:
  desc: null
  value: 1.0
exploration_rate:
  desc: null
  value: 0.0
exploration_schedule:
  desc: null
  value: <function get_linear_fn.<locals>.func at 0x7ffad033bf28>
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
learning_starts:
  desc: null
  value: 50000
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7ffaf20fac80>
max_grad_norm:
  desc: null
  value: 10
n_envs:
  desc: null
  value: 1
n_episodes_rollout:
  desc: null
  value: -1
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: Box(-3.4028234663852886e+38, 3.4028234663852886e+38, (4,), float32)
optimize_memory_usage:
  desc: null
  value: 'False'
policy:
  desc: null
  value: "DQNPolicy(\n  (q_net): QNetwork(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (q_net): Sequential(\n\
    \      (0): Linear(in_features=4, out_features=64, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=64, out_features=2, bias=True)\n    )\n  )\n  (q_net_target):\
    \ QNetwork(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (q_net): Sequential(\n      (0): Linear(in_features=4,\
    \ out_features=64, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=64,\
    \ out_features=2, bias=True)\n    )\n  )\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.dqn.policies.DQNPolicy'>
policy_kwargs:
  desc: null
  value: '{}'
policy_type:
  desc: null
  value: MlpPolicy
q_net:
  desc: null
  value: "QNetwork(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (q_net): Sequential(\n    (0): Linear(in_features=4, out_features=64,\
    \ bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=64, out_features=2,\
    \ bias=True)\n  )\n)"
q_net_target:
  desc: null
  value: "QNetwork(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (q_net): Sequential(\n    (0): Linear(in_features=4, out_features=64,\
    \ bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=64, out_features=2,\
    \ bias=True)\n  )\n)"
remove_time_limit_termination:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x7ffaf20f3630>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1626882542.815917
target_update_interval:
  desc: null
  value: 10000
tau:
  desc: null
  value: 1.0
tensorboard_log:
  desc: null
  value: runs/PPO_<stable_baselines3.common.vec_env.vec_video_recorder.VecVideoRecorder
    object at 0x7ffaf02ac3c8>
total_timesteps:
  desc: null
  value: 25000
train_freq:
  desc: null
  value: 4
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
